export { a } from "./HTMLAnchorElement.js";
export { area } from "./HTMLAreaElement.js";
export { audio } from "./HTMLAudioElement.js";
export { video } from "./HTMLVideoElement.js";
export { br } from "./HTMLBRElement.js";
export { button } from "./HTMLButtonElement.js";
export { canvas } from "./HTMLCanvasElement.js";
export { cite } from "./HTMLCiteElement.js";
export { data } from "./HTMLDataElement.js";
export { datalist } from "./HTMLDataListElement.js";
export { dialog } from "./HTMLDialogElement.js";
export { div } from "./HTMLDivElement.js";
export { dl } from "./HTMLListElement.js";
export { embed } from "./HTMLEmbedElement.js";
export { fieldset } from "./HTMLFieldSetElement.js";
export { form } from "./HTMLFormElement.js";
export { h1, h2, h3, h4, h5, h6 } from "./HTMLHeadingElement.js";
export { hr } from "./HTMLHRElement.js";
export { iframe } from "./HTMLIFrameElement.js";
export { img } from "./HTMLImageElement.js";
export { input, checkbox, color, date, datetimeLocal, email, file, hidden, image, month, number, password, radio, range, reset, search, submit, tel, text, url, week } from "./HTMLInputElement.js";
export { label } from "./HTMLLabelElement.js";
export { legend } from "./HTMLLegendElement.js";
export { li } from "./HTMLLIElement.js";
export { map } from "./HTMLMapElement.js";
export { menu } from "./HTMLMenuElement.js";
export { meter } from "./HTMLMeterElement.js";
export { ins, del } from "./HTMLModElement.js";
export { object } from "./HTMLObjectElement.js";
export { ol } from "./HTMLOListElement.js";
export { optgroup } from "./HTMLOptGroupElement.js";
export { option } from "./HTMLOptionElement.js";
export { output } from "./HTMLOutputElement.js";
export { p } from "./HTMLParagraphElement.js";
export { picture } from "./HTMLPictureElement.js";
export { pre } from "./HTMLPreElement.js";
export { progress } from "./HTMLProgressElement.js";
export { blockquote, q } from "./HTMLQuoteElement.js";
export { select } from "./HTMLSelectElement.js";
export { source } from "./HTMLSourceElement.js";
export { span } from "./HTMLSpanElement.js";
export { caption } from "./HTMLTableCaptionElement.js";
export { th, td } from "./HTMLTableCellElement.js";
export { colgroup, col } from "./HTMLTableColElement.js";
export { table } from "./HTMLTableElement.js";
export { tr } from "./HTMLTableRowElement.js";
export { thead, tbody, tfoot } from "./HTMLTableSectionElement.js";
export { textarea } from "./HTMLTextAreaElement.js";
export { time } from "./HTMLTimeElement.js";
export { track } from "./HTMLTrackElement.js";
export { ul } from "./HTMLUListElement.js";
